apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvwa-deployment
  namespace: vulnerables
  labels:
    app: dvwa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dvwa
  template:
    metadata:
      labels:
        app: dvwa
    spec:
      containers:
      - name: dvwa
        image: scotty2hotty/dvwa:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dvwa-svc
  namespace: vulnerables
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  externalTrafficPolicy: Local
  selector:
    app: dvwa
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
