apiVersion: apps/v1
kind: Deployment
metadata:
  name: shellshock-deployment
  namespace: vulnerables
  labels:
    app: shellshock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shellshock
  template:
    metadata:
      labels:
        app: shellshock
    spec:
      containers:
      - name: shellshock
        image: vulnerables/cve-2014-6271:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: shellshock-svc
  namespace: vulnerables
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  externalTrafficPolicy: Local
  selector:
    app: shellshock
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
